### ISSUE TITLE
Please publish 2.X.X releases to bintray

### ISSUE THREAD

**Issue by cruatta** [wireapp/lithium#10]
Can you please publish the 2.X.X releases of lithium to the wire-snapshots repo in bintray?

**Comment by dkovacevic** [comment]
Sorry for that. I will merge into `master` and publish it during the week. Meanwhile you can use the bleeding edge `2.8.1` built from `develop` branch published here:
```
<repository>
    <id>lithium</id>
    <url>https://packagecloud.io/dkovacevic/lithium/maven2</url>
    <releases>
        <enabled>true</enabled>
    </releases>
</repository>
```
