### ISSUE TITLE
Verification of Service Provider Account

### ISSUE THREAD

**Issue by fritsvt** [wireapp/lithium#14]
Hi Wire Devs,

Thanks for making this SDK! I'm looking forward to using it.

I am however now facing an issue whilst trying to setup a new service provider account. I used the bash script to create an account and I got an email that it has to be manually approved first.

The email stated it would take around 24 hours for the verification to complete.  But It has now been well over 24 hours and I have not heard back yet. 

I contacted customer support about this issue who said that they can not help with this and that I should seek for help at github.

I was wondering if something had gone wrong and if my account can be manually approved.

Thanks in advance and kind regards,

Frits

**Comment by rgutmann** [comment]
I wanted to use Wire for ChatOps and did the same about a month ago. I also did it a second time with a different email address after I've heard nothing for a week. 

I never received anything, so I started assuming that Wire does not really intend that it's service is used in ChatOps settings and I am now switching to another, less secure, chat collaboration service.

**Comment by dkovacevic** [comment]
We have temporarily issues with approvals currently. Should be back today or Monday. Sorry for this :'(

**Comment by dkovacevic** [comment]
This has been resolved. Please retry. Thanks for reporting.
