### ISSUE TITLE
Edit message

### ISSUE THREAD

**Issue by rothnorton** [wireapp/lithium#21]
1) Can you make an edit message option in WireClient?
Or is that what sendText(String txt, long expires, String messageId).
If so it doesn't seem to work for me (but that might be because the original message is being posted from a different device?).

2) Also, to facilitate, this how do you know how to get a list of msgId, msgText combos for a particular conversation.  Ie is the search feature available to bots? or is there a way of extracting it easily from the storage repo? Or can it be returned from a sendText call, and we can keep track of these ourselves?  The best I've been able to achieve is to post the message from a different device on the same bot account.  That way you can stored the message id / message text in the onText method.  However, onText isnt called for the bot that just posted the message.

Thanks

**Comment by dkovacevic** [comment]
> Can you make an edit message option in WireClient?
Or is that what sendText(String txt, long expires, String messageId).
If so it doesn't seem to work for me (but that might be because the original message is being posted from a different device?).

Edit Message feature is not supported yet. I will add it soon. _Timed Messages_ are supported (only if you are running in _Bot Mode_). 

> Also, to facilitate, this how do you know how to get a list of msgId, msgText combos for a particular conversation. Ie is the search feature available to bots? or is there a way of extracting it easily from the storage repo? Or can it be returned from a sendText call, and we can keep track of these ourselves? The best I've been able to achieve is to post the message from a different device on the same bot account. That way you can stored the message id / message text in the onText method. However, onText isnt called for the bot that just posted the message.

Bots cannot search. You should save messages into DB in your Bot logic in case you need to query them later. This SDK does not store messages in its storages. This is left for users to implement in their business logic layer

**Comment by rothnorton** [comment]
Sweet.  A workaround is to use client.deleteMessage() and then repost.

But for both cases, you need a message id.  So is there any way of getting the message id of a message sent with client.sendText()?  I couldnt work it out.

Like maybe there is a way to have the onText called for messages the bot sent itself (and then processing self messages differently)?

**Comment by dkovacevic** [comment]
Agree.
I suggest:
```
public String sendText(String txt) throws Exception {
        Text generic = new Text(txt);
        postGenericMessage(generic);
        return generic.getMessageId();
    }
```
The method will return the messageId used to send this text. Then you can use that messageId to delete/edit this message

**Comment by rothnorton** [comment]
Too easy. Shoulda seen that.  Thanks heaps. :)
