### ISSUE TITLE
Missing state exception in user mode

### ISSUE THREAD

**Issue by rothnorton** [wireapp/lithium#24]
Since the recent message edit update I'm getting the following error whenever message received.
com.wire.bots.sdk.exceptions.MissingStateException: Unknown botId: xxxxxxxxxx
	at com.wire.bots.sdk.state.RedisState.getState(RedisState.java:71)
	at com.wire.bots.sdk.user.UserClientRepo.getWireClient(UserClientRepo.java:22)
	at com.wire.bots.sdk.user.UserMessageResource.onNewMessage(UserMessageResource.java:32)

Bot is running in user mode.  The issue doesnt occur when not running in nonuser mode.

**Comment by dkovacevic** [comment]
The `State` object is stored in Redis db (unless you use the File System state storage).
Can you check and verify Redis has json data for `key=<botId>`
When running in `UserMode` the state is persisted as soon as you call: 
`com.wire.bots.sdk.user.Endpoint::signIn(...)`

**Comment by rothnorton** [comment]
Yeah wasn't sure if somehow the state got corrupted, had issues with something i'd customised or it was due to the recent change to persistence introduced.
I've stopped using user mode, so cannot look into that atm, apologies.
If it's working for you it's probably something I did.

**Comment by dkovacevic** [comment]
You are right. It got broken (somehow). ver2.22.4 should have it fixed.
Thank you for reporting!
