### ISSUE TITLE
What are the client login restrictions?

### ISSUE THREAD

**Issue by patsan303** [wireapp/lithium#29]
```
Exception in thread "main" HttpException: {"code":429,"message":"Logins too frequent","label":"client-error"}, status: 429
	at com.wire.bots.sdk.user.LoginClient.login(LoginClient.java:67)
	at com.wire.bots.sdk.user.Endpoint.signIn(Endpoint.java:81)
	at com.wire.bots.echo.Main.main(Main.java:44)
```

How many logins are allowed over what time period?

**Comment by fisx** [comment]
The simple answer is: as long as you never have more than 32 cookies, you're fine.

If you hit that limit, the algorithm is a bit complicated and depends on the creation dates of all existing cookies](https://github.com/wireapp/wire-server/blob/cee28d28eeb1a845eab33ae754cbc44ce467b89e/services/brig/src/Brig/User/Auth/Cookie/Limit.hs#L71-L82).  The settings on our system are:

```
dev = 3000
del = 1 day
```

So if the standard deviation of all cookie creation dates exceeds 3000, you will get blocked for 1 day minus the creation time of the youngest cookie.

But with some luck "don't ever have more than 32 cookies per user and you'll be fine" is already a good enough answer?

Please let me know if this helps!
